create table "public"."menuids" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "menuid" bigint
);


alter table "public"."menuids" enable row level security;

create table "public"."sportsdates" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "start_date" date default now()
);


alter table "public"."sportsdates" enable row level security;

CREATE UNIQUE INDEX menuids_pkey ON public.menuids USING btree (id);

CREATE UNIQUE INDEX sportsdates_pkey ON public.sportsdates USING btree (id);

alter table "public"."menuids" add constraint "menuids_pkey" PRIMARY KEY using index "menuids_pkey";

alter table "public"."sportsdates" add constraint "sportsdates_pkey" PRIMARY KEY using index "sportsdates_pkey";

grant delete on table "public"."menuids" to "anon";

grant insert on table "public"."menuids" to "anon";

grant references on table "public"."menuids" to "anon";

grant select on table "public"."menuids" to "anon";

grant trigger on table "public"."menuids" to "anon";

grant truncate on table "public"."menuids" to "anon";

grant update on table "public"."menuids" to "anon";

grant delete on table "public"."menuids" to "authenticated";

grant insert on table "public"."menuids" to "authenticated";

grant references on table "public"."menuids" to "authenticated";

grant select on table "public"."menuids" to "authenticated";

grant trigger on table "public"."menuids" to "authenticated";

grant truncate on table "public"."menuids" to "authenticated";

grant update on table "public"."menuids" to "authenticated";

grant delete on table "public"."menuids" to "service_role";

grant insert on table "public"."menuids" to "service_role";

grant references on table "public"."menuids" to "service_role";

grant select on table "public"."menuids" to "service_role";

grant trigger on table "public"."menuids" to "service_role";

grant truncate on table "public"."menuids" to "service_role";

grant update on table "public"."menuids" to "service_role";

grant delete on table "public"."sportsdates" to "anon";

grant insert on table "public"."sportsdates" to "anon";

grant references on table "public"."sportsdates" to "anon";

grant select on table "public"."sportsdates" to "anon";

grant trigger on table "public"."sportsdates" to "anon";

grant truncate on table "public"."sportsdates" to "anon";

grant update on table "public"."sportsdates" to "anon";

grant delete on table "public"."sportsdates" to "authenticated";

grant insert on table "public"."sportsdates" to "authenticated";

grant references on table "public"."sportsdates" to "authenticated";

grant select on table "public"."sportsdates" to "authenticated";

grant trigger on table "public"."sportsdates" to "authenticated";

grant truncate on table "public"."sportsdates" to "authenticated";

grant update on table "public"."sportsdates" to "authenticated";

grant delete on table "public"."sportsdates" to "service_role";

grant insert on table "public"."sportsdates" to "service_role";

grant references on table "public"."sportsdates" to "service_role";

grant select on table "public"."sportsdates" to "service_role";

grant trigger on table "public"."sportsdates" to "service_role";

grant truncate on table "public"."sportsdates" to "service_role";

grant update on table "public"."sportsdates" to "service_role";

create policy "Allow authenticated users to insert"
on "public"."menuids"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."menuids"
as permissive
for select
to public
using (true);


create policy "Allow authenticated users to insert"
on "public"."menus"
as permissive
for insert
to authenticated
with check (true);


create policy "Allow authenticated users to insert"
on "public"."schedules"
as permissive
for insert
to authenticated
with check (true);


create policy "Allow authenticated users to insert"
on "public"."sportsdates"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."sportsdates"
as permissive
for select
to public
using (true);



