create table "public"."menus" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "day" date not null default now(),
    "menu" json not null default '{}'::json
);


create table "public"."schedules" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "day" date not null default now(),
    "schedule" json not null default '{}'::json
);


CREATE UNIQUE INDEX menus_pkey ON public.menus USING btree (id);

CREATE UNIQUE INDEX schedules_pkey ON public.schedules USING btree (id);

alter table "public"."menus" add constraint "menus_pkey" PRIMARY KEY using index "menus_pkey";

alter table "public"."schedules" add constraint "schedules_pkey" PRIMARY KEY using index "schedules_pkey";

grant delete on table "public"."menus" to "anon";

grant insert on table "public"."menus" to "anon";

grant references on table "public"."menus" to "anon";

grant select on table "public"."menus" to "anon";

grant trigger on table "public"."menus" to "anon";

grant truncate on table "public"."menus" to "anon";

grant update on table "public"."menus" to "anon";

grant delete on table "public"."menus" to "authenticated";

grant insert on table "public"."menus" to "authenticated";

grant references on table "public"."menus" to "authenticated";

grant select on table "public"."menus" to "authenticated";

grant trigger on table "public"."menus" to "authenticated";

grant truncate on table "public"."menus" to "authenticated";

grant update on table "public"."menus" to "authenticated";

grant delete on table "public"."menus" to "service_role";

grant insert on table "public"."menus" to "service_role";

grant references on table "public"."menus" to "service_role";

grant select on table "public"."menus" to "service_role";

grant trigger on table "public"."menus" to "service_role";

grant truncate on table "public"."menus" to "service_role";

grant update on table "public"."menus" to "service_role";

grant delete on table "public"."schedules" to "anon";

grant insert on table "public"."schedules" to "anon";

grant references on table "public"."schedules" to "anon";

grant select on table "public"."schedules" to "anon";

grant trigger on table "public"."schedules" to "anon";

grant truncate on table "public"."schedules" to "anon";

grant update on table "public"."schedules" to "anon";

grant delete on table "public"."schedules" to "authenticated";

grant insert on table "public"."schedules" to "authenticated";

grant references on table "public"."schedules" to "authenticated";

grant select on table "public"."schedules" to "authenticated";

grant trigger on table "public"."schedules" to "authenticated";

grant truncate on table "public"."schedules" to "authenticated";

grant update on table "public"."schedules" to "authenticated";

grant delete on table "public"."schedules" to "service_role";

grant insert on table "public"."schedules" to "service_role";

grant references on table "public"."schedules" to "service_role";

grant select on table "public"."schedules" to "service_role";

grant trigger on table "public"."schedules" to "service_role";

grant truncate on table "public"."schedules" to "service_role";

grant update on table "public"."schedules" to "service_role";


